#! /usr/bin/python
import sys, os, argparse, zipfile, warnings
from lxml import etree as ET

parser = argparse.ArgumentParser(description="Add or modify author metadata of ODT file")

parser.add_argument('document', help="Path/filename of ODT file")
parser.add_argument('authors', help="Author string to embed in the ODT metadata")

args = parser.parse_args()

# Ensure we can cope with Unicode
authors = args.authors.decode(sys.getfilesystemencoding())

# Extract metadata
with zipfile.ZipFile(args.document, 'a') as odtfile:
    metadata = odtfile.read('meta.xml')

    # Change or add author metadata
    root = ET.fromstring(metadata)
    metaElement = root.find('office:meta', root.nsmap)
    if metaElement == None:
        print "Cannot find office:meta element. Something is wrong."
        exit(1)
    authorElement = metaElement.find('meta:initial-creator', root.nsmap)
    if authorElement == None:
        print "Cannot find meta:initial-creator element. Creating one."
        authorElement = ET.Element('{urn:oasis:names:tc:opendocument:xmlns:meta:1.0}initial-creator')
        authorElement.text = authors
        metaElement.append(authorElement)
    else:
        print "Found meta:initial-creator element. Updating."
        authorElement.text = authors

    # Update file, suppressing the warning about overwriting
    newMetadata = ET.tostring(root)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=UserWarning)
        odtfile.writestr('meta.xml', newMetadata)

print "Success!"
