#! /usr/bin/python
import sys, os, argparse
from lxml import etree as ET

parser = argparse.ArgumentParser(description="Add or modify author metadata of ODT file")

parser.add_argument('document', help="Path/filename of ODT file")
parser.add_argument('authors', help="Author string to embed in the ODT metadata")

args = parser.parse_args()

# Ensure we can cope with Unicode
authors = args.authors.decode(sys.getfilesystemencoding())

# Extract metadata
os.system("unzip {0} meta.xml".format(args.document))

# Change or add author metadata
tree = ET.parse('meta.xml')
root = tree.getroot()
metaElement = root.find('office:meta', root.nsmap)
if metaElement == None:
    print "Cannot find office:meta element. Something is wrong."
    exit(1)
authorElement = metaElement.find('meta:initial-creator', root.nsmap)
if authorElement == None:
    print "Cannot find meta:initial-creator element. Creating one."
    authorElement = ET.Element('{urn:oasis:names:tc:opendocument:xmlns:meta:1.0}initial-creator')
    authorElement.text = authors
    metaElement.append(authorElement)
else:
    print "Found meta:initial-creator element. Updating."
    authorElement.text = authors

tree.write('meta.xml')

# Reinsert metadata
os.system("zip -u {0} meta.xml".format(args.document))

# Tidy up
os.system('rm meta.xml')

print "Success!"
