#! /bin/sh

mkdir -p "thumbnails"
for pdf in *.pdf; do
  echo "Examining $pdf..."
  size=`identify -format "%[fx:w/72]x%[fx:h/72]" $pdf`
  width=`echo $size | cut -f1 -dx`
  height=`echo $size | cut -f2 -dx`
  echo "$pdf is $width by $height inches..."
  hifactor=`echo "scale=5; sqrt((sqrt(2)*5600^2)/($width*$height))" | bc`
  lofactor=`echo "scale=5; sqrt((sqrt(2)*350^2)/($width*$height))" | bc`
  echo "Sampling at a density of $hifactor PPI (aliased), $lofactor PPI (anti-aliased)..."
  convert -background white -alpha Remove -density $hifactor -resample $lofactor $pdf "thumbnails/${pdf%.pdf}.jpg"
done

echo "Finished!"
